import Image from "next/image";
import { motion } from "framer-motion";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";
import UserProfile from "../components/Profile";
import Link from "next/link";
// import atm from "../public/atm.svg";

export default function Component() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Dashboard | Citizens Farmers Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-img.png" />
      </Head>
      <main className="xs:mx-32 mx-5">
        {/* Welcome section for dashboard and signout button*/}
        <motion.section
          className="flex justify-between pb-3"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.0 }}
        >
          <h1 className="font-semibold xs:text-[28px] tracking-wide">
            ACCOUNT OVERVIEW
          </h1>
          <button
            onClick={signOut}
            className="text-green-600 font-semibold border rounded-md border-green-300 px-1 hover:bg-green-600 hover:text-white"
          >
            Sign out
          </button>
        </motion.section>

        <motion.section
          className="xs:pl-2"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.2 }}
        >
          <div className="xs:flex justify-around">
            <h1 className="font-semibold text-[12px] xs:text-[18px] uppercase pb-5 xs:pb-5">
              <span className="text-[10px] xs:text-[14px] font-semibold">
                Signed in as:
              </span>{" "}
              {session?.user?.fullName}
            </h1>
            <h1 className="font-semibold text-[12px] xs:text-[18px] uppercase pb-5 xs:pb-5">
              <span className="text-[10px] xs:text-[14px] font-semibold">
                Account Number:
              </span>{" "}
              {session?.user?.accountNo}
            </h1>
            <h1 className="font-semibold text-[12px] xs:text-[18px] uppercase pb-5 xs:pb-5">
              <span className="text-[10px] xs:text-[14px] font-semibold">
                Routing Number:
              </span>{" "}
              {session?.user?.routingNo}
            </h1>
          </div>
          {/* <UserProfile /> */}
          <div className="justify-between xs:pb-5 items-center">
            <h1 className="font-semibold text-[12px] xs:text-[18px] xs:pt-3 pb-2">
              Account balance
            </h1>
          </div>
        </motion.section>
        {/* ACCOUNT BALANCE CARD */}
        <motion.section
          className="xs:flex xs:justify-around px-10"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.3 }}
        >
          <div className="border rounded-md shadow-md xs:pt-10 xs:px-20 xs:pb-10 p-3 text-center">
            <h3 className="font-semibold pb-3">Current Account</h3>
            <p className="font-bold text-green-600">
              {session?.user?.current} <span className="text-[12px]">USD</span>
            </p>
          </div>
          <br />
          <div className="border rounded-md shadow-md xs:pt-10 xs:px-20 xs:pb-10 p-3 text-center">
            <h3 className="font-semibold pb-3">Available Balance:</h3>
            <p className="font-bold text-green-600">
              {session?.user?.available}{" "}
              <span className="text-[12px]">USD</span>
            </p>
          </div>
          <br />
          <div className="border rounded-md shadow-md xs:pt-10 xs:px-20 xs:pb-10 p-3 text-center">
            <h3 className="font-semibold pb-3">Savings Balance:</h3>
            <p className="font-bold text-green-600">
              {session?.user?.savings} <span className="text-[12px]">USD</span>
            </p>
          </div>
        </motion.section>

        {/* MONEY GRAPH AND SEND MONEY */}
        <motion.section
          className="xs:flex xs:justify-evenly xs:items-center xs:pt-10"
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
        >
          <div className="bg-gray-700 xs:px-20 p-5 w-fit m-auto mt-10">
            <form method="POST">
              <h3 className="font-semibold text-gray-100 text-center pb-2">
                TRANSFER MONEY
              </h3>
              <label className="block text-[14px] text-gray-100">
                Beneficiary Account Number
              </label>
              <input
                className="block border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                id="grid-password"
                type="text"
                required
              />
              <label className="block text-[14px] text-gray-100">Amount</label>
              <input
                className="block border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                id="amount"
                type="money"
                placeholder="$50,000.00"
              />

              <label className="block text-[14px] text-gray-100" htmlFor="">
                Transcation Note
              </label>
              <textarea
                placeholder="Naration"
                className="border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
              />
              <button
                type="submit"
                className="block bg-transparent hover:bg-white hover:text-black border rounded p-2"
                onClick={function tax() {
                  alert("Make update on your tax payment");
                }}
              >
                <span className="text-gray-200 hover:text-black">Transfer</span>
              </button>
            </form>
          </div>
          <Image
            alt="graph"
            src="/graph.svg"
            width={300}
            height={300}
            className="p-3 mt-5 w-auto h-auto"
          />
        </motion.section>
        <motion.section
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="p-10 text-center text-lg font-bold"
        >
          <h1 className="xs:p-10 p-2 text-center text-lg font-bold">
            PAYBILLS
          </h1>
          <div className="xs:flex gap-5 m-3 justify-center">
            <select
              name="Select bill"
              id="Select bill"
              className="py-2 px-5 border border-gray-500 text-sm"
            >
              <option className="bg-gray-200" value="water">
                Water
              </option>
              <option className="bg-gray-200" value="gas">
                Gas
              </option>
              <option className="bg-gray-200" value="water">
                Internet
              </option>
              <option className="bg-gray-200" value="water">
                Electricity
              </option>
              <option className="bg-gray-200" value="water">
                Phone bill
              </option>
              <option className="bg-gray-200" value="water">
                Tv Bill
              </option>
            </select>
            <select
              name="City"
              id="City"
              className="py-2 px-5 border border-gray-500  text-sm"
            >
              <option className="bg-gray-200" value="water">
                Alabama
              </option>
              <option className="bg-gray-200" value="gas">
                Alaska
              </option>
              <option className="bg-gray-200" value="water">
                Arizona
              </option>
              <option className="bg-gray-200" value="water">
                Arkansas
              </option>
              <option className="bg-gray-200" value="water">
                California
              </option>
              <option className="bg-gray-200" value="water">
                Colorado
              </option>
              <option className="bg-gray-200" value="water">
                Florida
              </option>
              <option className="bg-gray-200" value="water">
                Georgia
              </option>
              <option className="bg-gray-200" value="water">
                Illinois
              </option>
              <option className="bg-gray-200" value="water">
                Kansas
              </option>
              <option className="bg-gray-200" value="water">
                Massachusetts
              </option>
              <option className="bg-gray-200" value="water">
                New Jersey
              </option>
              <option className="bg-gray-200" value="water">
                New York
              </option>
              <option className="bg-gray-200" value="water">
                Texas
              </option>
            </select>
            <input
              type="text"
              placeholder="Mobile Number"
              className="p-1 w-[8rem] border border-gray-500 text-sm"
            />
            <input
              type="text"
              placeholder="Street number & name"
              className="p-1 w-[5rem] border border-gray-500 text-sm"
            />
            <input
              type="text"
              placeholder="Amount"
              className="p-1 w-[5rem] border border-gray-500 text-sm"
            />
            <button
              type="submit"
              onClick={() =>
                alert("Can not pay bills now. Update tax payment first.")
              }
              className="p-1 w-[5rem] bg-green-600 border border-gray-500 text-sm text-gray-100"
            >
              Pay
            </button>
          </div>
        </motion.section>
        {/* TRANSACTION HISTORY */}
        <motion.section
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
        >
          <h2 className="xs:px-14 xs:pt-10 font-semibold">
            Transaction History
          </h2>
          <h2 className="xs:px-20 pt-5 xs:text-[18] text-[12px] font-semibold pb-5">
            Filter by:{" "}
            <span className="bg-green-500 px-2 text-white">
              Type<select className="bg-green-500"></select>
            </span>
          </h2>
          <div className="xs:mx-14 pb-10 border border-gray-600">
            <div className="flex p-3 bg-green-600 justify-between text-white">
              <h3>Type</h3>
              <h3>Date</h3>
              <h3>Details</h3>
              <h3>Amount</h3>
              <h3>Balance</h3>
            </div>
            <p className="text-center pt-3 font-semibold">
              No Transaction has been made
            </p>
          </div>
        </motion.section>
      </main>
    </>
  );
}
