import React from "react";
import Head from "next/head";
import Popup from "reactjs-popup";
import Image from "next/image";
import { aleaRNGFactory } from "number-generator";

function dash() {
  const generator = aleaRNGFactory(2);
  return (
    <>
      <Head>
        <title>Dashboard | Citizens Farmers Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-img.png" />
      </Head>
      <main className="xs:px-32 xs:py-20 bg-gray-700">
        <div className="xs:flex justify-between items-center pt-10">
          <h1 className="font-burtons xs:text-[28px] text-[14px] pl-2 text-gray-100 tracking-wider">
            DASHBOARD
          </h1>
          <div className="flex pl-2">
            <p className="text-gray-300">Signed in as: D.s.uzoegbu@gmail.com</p>
            <button
              type="submit"
              className="bg-red-500 text-white font-opensans text-[14px] ml-1 p-1 rounded"
            >
              sign out
            </button>
          </div>
        </div>
        {/* account details */}
        <div className="pl-2">
          <p className="font-opensans text-gray-400 font-semibold">
            Account No. 0101{generator.uInt32()}
          </p>
          <p className="font-opensans text-gray-400 font-semibold">
            Routine No. 14-{generator.uInt32()}
          </p>
        </div>
        {/* ACCOUNT BALANCE SHOWS HERE */}
        <div className="xs:flex ">
          <div className="pt-10 px-5">
            <p className="font-opensans pb-5 text-green-500 font-bold text-[13px] xs:text-[24px] tracking-wide">
              ACCOUNT OVERVIEW
            </p>
            <p className="font-opensans text-gray-300 font-semibold pb-2 text-[12px] xs:text-[18px]">
              Current Balance:
              <span className="font-bold text-gray-300 text-[12px] xs:text-[18px] pl-1">
                $5,000,000.00 <span className="text-red-500">USD</span>
              </span>
            </p>
            <p className="font-opensans text-gray-300 font-semibold pb-2 text-[12px] xs:text-[18px]">
              Available Balance:
              <span className="font-bold text-gray-300 text-[12px] xs:text-[18px] pl-1">
                $500,000.00 <span className="text-red-500">USD</span>
              </span>
            </p>
            <p className="font-opensans text-gray-300 font-semibold pb-2 text-[12px] xs:text-[18px]">
              Savings Balance:
              <span className="font-bold text-gray-300 text-[12px] xs:text-[18px] pl-1">
                $100,000.00 <span className="text-red-500">USD</span>
              </span>
            </p>
            <div className="pt-10">
              <Popup
                trigger={
                  <button className="button hover:pointer-cursor bg-gray-100 border border-gray-800 shadow-md shadow-slate-700 py-2 px-4 rounded font-opensans">
                    Send money
                  </button>
                }
                modal
                nested
              >
                {(close) => (
                  <div className="bg-white min-h-min p-5">
                    <div className="flex pb-10">
                      <button
                        className="close px-1 rounded-md bg-red-700 text-white"
                        onClick={close}
                      >
                        &times;
                      </button>
                      <div className="header pl-10 font-opensans font-bold text-green-500 text-[18px]">
                        SEND MONEY
                      </div>
                    </div>
                    <label
                      class="block uppercase text-[12px] text-gray-400 text-xs font-opensans font-bold mb-2"
                      for="grid-password"
                    >
                      Amount
                    </label>
                    <input
                      class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                      id="grid-password"
                      type="number"
                      placeholder="$50,000.00"
                    />
                    <label
                      class="block uppercase text-[12px] text-gray-400 text-xs font-opensans font-bold mb-2"
                      for="grid-password"
                    >
                      Beneficiary Account Number
                    </label>
                    <input
                      class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                      id="grid-password"
                      type="tel"
                    />
                    <label
                      class="block uppercase text-[12px] text-gray-400 text-xs font-opensans font-bold mb-2"
                      for="grid-password"
                    >
                      Transcation Note
                    </label>
                    <textarea
                      class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                      id="grid-password"
                    />
                    <div className="action">
                      <Popup
                        trigger={<button className="button"> Send </button>}
                        position="top center"
                        nested
                      >
                        <div className="bg-white w-1/3 m-auto p-5">
                          <Image
                            alt=""
                            src="/error.svg"
                            width={50}
                            height={50}
                          />
                          <span className="font-opensans">
                            Can not make transfer now. Pay tax first
                          </span>
                        </div>
                      </Popup>
                      <button
                        className="button"
                        onClick={() => {
                          console.log("modal closed ");
                          close();
                        }}
                      >
                        close modal
                      </button>
                    </div>
                  </div>
                )}
              </Popup>
            </div>
          </div>
          <div class="min-w-min m-auto p-10 mt-5 bg-gray-800 justify-center">
            <form class="shadow-lg w-full max-w-lg">
              <p className="font-opensans font-bold text-gray-300 text-[12px] xs:text-[18px]">
                ENTER DETAILS TO CONFIRM ACCOUNT
              </p>
              <span className="font-opensansitalic font-bold text-green-500 text-[8px] xs:text-[10px] pb-5">
                YOUR DETAILS ARE SAFE
              </span>
              <div class="flex flex-wrap -mx-3">
                <div class="w-full px-3">
                  <label
                    class="block uppercase tracking-wide text-gray-400 text-xs font-opensans font-bold mb-2"
                    for="grid-password"
                  >
                    Email
                  </label>
                  <input
                    class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-password"
                    type="email"
                  />
                  <label
                    class="block uppercase tracking-wide text-gray-400 text-xs font-opensans font-bold mb-2"
                    for="grid-email"
                  >
                    Social Security Number
                  </label>
                  <input
                    class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-password"
                    type="text"
                    placeholder="******************"
                  />
                  <label
                    class="block uppercase tracking-wide text-gray-400 text-xs font-opensans font-bold mb-2"
                    for="grid-email"
                  >
                    Tax Number
                  </label>
                  <input
                    class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    id="grid-password"
                    type="text"
                    placeholder="******************"
                  />
                  <p class="text-gray-600 mb-3 text-xs italic">
                    Input a secure password
                  </p>
                </div>
              </div>
              <div class="flex flex-wrap -mx-3 mb-2">
                {/* REGISTRATION SUBMIT BUTTON */}
                <div className="justify-right px-3 pt-5 mb-6 md:mb-0">
                  <input
                    type="submit"
                    className="px-10 py-2 font-opensans font-bold text-gray-400 text-[14px] bg-gray-700 rounded border border-gray-600"
                  />
                </div>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}

export default dash;
