import Head from "next/head";
import { motion } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import card from "../public/card.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Citizens Farmer Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-img.png" />
      </Head>

      <main className="mx-40 mv:m-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.0 }}
        >
          <ul className="flex mx-5 justify-center space-x-5">
            <Link
              href="/about"
              className="cursor-pointer font-bold text-[12px] text-gray-700 hover:text-green-600 "
            >
              About Us
            </Link>
            <Link
              href="/contact"
              className="cursor-pointer font-bold text-[12px] text-gray-700 hover:text-green-600 "
            >
              Contact Us
            </Link>
            <Link
              href="/"
              className="cursor-pointer font-bold text-[12px] text-gray-700 hover:text-green-600"
            >
              FaQ
            </Link>
            <Link 
              href="/login"
              // { callbackUrl: 'http://localhost:3000/dashboard' }
              className="cursor-pointer font-bold text-[12px] text-red-700 hover:text-red-500 "
            >
              Login
            </Link>
          </ul>
        </motion.div>

        <motion.span
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.0 }}
          className="flex justify-center items-center gap-2 bg-green-500 text-green-100 mv:text-[10px] xs:text-[14px]"
        >
          <span className="font-bold text-green-700 mv:text-[13px] xs:text-[18px]">
            Updates:
          </span>
          Get upto 4% on our Savings Account Balances with Citizens Farmers Bank
        </motion.span>

        {/* Promo Advert ends here */}

        <section
          id="hero"
          className="xs:h-screen"
          style={{
            backgroundImage: "url('/hero.jpg')",
          }}
        >
          <div className="text-center text-white font-bold xs:flex-1 xs:text-center">
            <motion.div
              className="pt-36"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1.5 }}
            >
              <span className="text-[14px] xs:text-[30px]">
                Welcome to <br />
                <span className="text-white text-xl xs:text-[4rem]">
                  Citizen Farmers Bank.
                </span>
              </span>
              <p className="text-transparent text-x xs:text-1xl xs:mt-5">
                Create an account now!.
              </p>
              {/* DESKTOP VIEW CREATE USER-ACCOUNT BUTTON */}
              <div className="gap-2 text-center hidden xs:flex xs:justify-center xs:mt-10">
                <button className="bg-white hover:bg-gradient-to-r hover:from-green-400 hover:to-green-600 leading-0 px-6 py-2 rounded-md">
                  <Link href="/signup">
                    <span className="text-[16px] text-green-500 hover:text-white">
                      Create Account
                    </span>
                  </Link>
                </button>
                <button className="bg-green-500 hover:bg-gradient-to-r hover:from-green-400 hover:to-green-600 text-teal-900 leading-0 px-6 py-2 rounded-md">
                  <Link href="/about">
                    <span className="text-[16px] text-white">Learn more</span>
                  </Link>
                </button>
              </div>
              {/*   MOBILE VIEW CREATE USER-ACCOUNT BUTTON  */}
              <div className="flex gap-3 justify-center p-10">
                <div className="xs:hidden">
                  <button className="bg-white leading-0 px-1 py-1 rounded-sm ">
                    <Link href="/signup">
                      <span className="text-[10px] text-green-500">
                        Create Account
                      </span>
                    </Link>
                  </button>
                </div>
                <div className="xs:hidden">
                  <button className="bg-green-500 leading-0 px-1 py-1 rounded-sm ">
                    <Link href="/about">
                      <span className="text-[10px]">Learn more</span>
                    </Link>
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        </section>
        <section id="2">
          <div className="text-gray-500 text-center mt-10">
            __________________________________
          </div>

          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 2.0 }}
            className="flex gap-2 font-bold justify-center items-center mt-10 mv:text-center mv:gap-1"
          >
            <Image
              alt=""
              src="/users.svg"
              width={30}
              height={30}
              className="mv:w-5 mv:h-5"
            />
            <h3 className="bold text-[13px]">3800+ USER ACTIVE</h3>
            <Image
              alt=""
              src="/random-building.svg"
              width={30}
              height={30}
              className="w-30 h-30 mv:w-5 mv:h-5"
            />
            <h3 className="font-bold text-[13px]">230+ TRUSTED BY COMPANY</h3>
            <Image
              alt=""
              src="/profitcurve.svg"
              width={30}
              height={30}
              className="mv:w-5 mv:h-5"
            />
            <h3 className="font-bold text-[13px]">$230M+ TRANSACTION</h3>
          </motion.div>
        </section>
        {/* Our feature section starts here */}
        <section
          className="mt-10 xs:p-20 bg-gray-900 flex justify-center"
          id="section1"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 2.0 }}
            className="text-center items-center mv:text-center"
          >
            <h1 className="mt-5 text-white text-xl xs:text-3xl">
              Our Features
            </h1>

            {/* OUR FEATURE SECTION CONTENT 1*/}
            <div className="xs:flex xs:justify-between mv:mt-10 mv:text-[10px]">
              <Image
                alt=""
                width={400}
                height={400}
                src={card}
                className="m-5 xs:w-64 md:w-auto"
              />

              <p className="text-gray-400 text-[12px] xs:text-[12px] xs:mt-40 md:text-[16px]">
                - Make payment by linking your paypal account.
                <br /> - Our platform is fast and reliable to use.
                <br /> - See accuract statistical values.
                <br /> - Quick transaction.
              </p>
            </div>
            {/*  SECTION CONTENT 2 */}
            <div className="xs:flex pt-20 mt-20 justify-between w-[]">
              <div className="flex-1 text-white">
                <span className="font-bold text-[24px] md:text-[16px]">
                  YOU DO THE BUSINESS, <br />
                  WE WILL HANDLE YOUR MONEY.
                </span>
                <span className="text-gray-400 text-[13px] md:text-[16px]">
                  <br />
                  With the right credit card, you can improve your financial
                  life by building credit, earning rewards and saving money. But
                  with hundreds of credit cards on the market.
                </span>
              </div>
              <div className="xs:flex">
                <div className="xs:flex w-[300px]">
                  <svg
                    width="54"
                    height="54"
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                      cx="32"
                      cy="32"
                      r="32"
                      fill="#05B313"
                      fillOpacity="0.1"
                    />
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M31.565 47.8619C31.7422 47.9544 31.9403 48.0015 32.1384 47.9999C32.3365 47.9984 32.5331 47.9497 32.7119 47.8556L38.4205 44.8039C40.0393 43.941 41.307 42.9761 42.296 41.8527C44.4464 39.4051 45.6206 36.2813 45.5997 33.0602L45.5321 22.4352C45.5256 21.2114 44.7218 20.1194 43.5331 19.7224L32.9132 16.1593C32.2737 15.9428 31.573 15.9475 30.9448 16.1703L20.3652 19.8605C19.1829 20.2731 18.3936 21.373 18.4001 22.5983L18.4677 33.2155C18.4887 36.4413 19.7032 39.551 21.889 41.9735C22.8877 43.0812 24.1667 44.032 25.8032 44.8808L31.565 47.8619ZM30.0538 35.3743C30.2922 35.6034 30.6014 35.7163 30.9107 35.7132C31.22 35.7116 31.5276 35.5955 31.7628 35.3633L38.0014 29.213C38.4701 28.7501 38.4653 28.0064 37.9917 27.5498C37.5165 27.0933 36.7514 27.0964 36.2826 27.5593L30.893 32.8718L28.6862 30.7505C28.211 30.294 27.4475 30.2987 26.9772 30.7615C26.5084 31.2244 26.5133 31.9681 26.9884 32.4246L30.0538 35.3743Z"
                      fill="#05B313"
                    />
                  </svg>
                  <h1 className="text-green-500 font-bold text-[14px]">
                    100% Secured
                    <br />
                    <span className="text-white font-normal text-[12px]">
                      We take proactive steps make sure your information and
                      transactions are secure.
                    </span>
                  </h1>
                </div>
                <div className="xs:flex w-[300px]">
                  <svg
                    width="54"
                    height="54"
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                      cx="32"
                      cy="32"
                      r="32"
                      fill="#05B313"
                      fillOpacity="0.1"
                    />
                    <path
                      d="M41.4696 35.7122C41.0552 36.1138 40.8648 36.6946 40.9592 37.2642L42.3816 45.1362C42.5016 45.8034 42.22 46.4786 41.6616 46.8642C41.1144 47.2642 40.3864 47.3122 39.7896 46.9922L32.7032 43.2962C32.4568 43.165 32.1832 43.0946 31.9032 43.0866H31.4696C31.3192 43.109 31.172 43.157 31.0376 43.2306L23.9496 46.9442C23.5992 47.1202 23.2024 47.1826 22.8136 47.1202C21.8664 46.941 21.2344 46.0386 21.3896 45.0866L22.8136 37.2146C22.908 36.6402 22.7176 36.0562 22.3032 35.6482L16.5256 30.0482C16.0424 29.5794 15.8744 28.8754 16.0952 28.2402C16.3096 27.6066 16.8568 27.1442 17.5176 27.0402L25.4696 25.8866C26.0744 25.8242 26.6056 25.4562 26.8776 24.9122L30.3816 17.7282C30.4648 17.5682 30.572 17.421 30.7016 17.2962L30.8456 17.1842C30.9208 17.101 31.0072 17.0322 31.1032 16.9762L31.2776 16.9122L31.5496 16.8002H32.2232C32.8248 16.8626 33.3544 17.2226 33.6312 17.7602L37.1816 24.9122C37.4376 25.4354 37.9352 25.7986 38.5096 25.8866L46.4616 27.0402C47.1336 27.1362 47.6952 27.6002 47.9176 28.2402C48.1272 28.8818 47.9464 29.5858 47.4536 30.0482L41.4696 35.7122Z"
                      fill="#05B313"
                    />
                  </svg>
                  <h1 className="text-green-500 font-bold text-[14px]">
                    Rewards <br />{" "}
                    <span className="text-white font-normal text-[12px]">
                      The best credit cards offer some tantalizing combinations
                      of promotions and prizes
                    </span>
                  </h1>
                </div>
              </div>
            </div>
          </motion.div>
        </section>
        {/* Our feature section ends here */}

        {/* NEWS LETTER */}
        <div className="bg-gray-900 mv:pt-20 mv:text-center">
          <span className="text-white text-[18px]">Get updates from us</span>
        </div>

        <div className="pt-5 flex justify-center items-center bg-gray-900 px-20 gap-1 pb-20">
          <input
            type="text"
            className="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            placeholder="Email Address"
          />
          <input
            type="submit"
            className="bg-green-500 hover:bg-green-500 text-green-700 font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded"
          />
        </div>
        {/* PICTURE SECTION */}
        <div
          className="pb-20 xs:h-[50vh]"
          style={{
            backgroundImage: "url('/hero1.jpg')",
          }}
        ></div>
      </main>
    </>
  );
}
